DATASET_NAME: ShapeNet55
DATA_ROOT: data/ShapeNet55

NUM_CLASSES: 55
NUM_PARTIAL_POINTS: 2048
NUM_GT_POINTS: 8192

NUM_PC: 256
NUM_P0: 512
UP_FACTORS: [1, 4, 4]

BATCH_SIZE: 16
NUM_WORKERS: 8
MAX_EPOCH: 300
LR: 0.0001
STEP_SIZE: 50
GAMMA: 0.5
WEIGHT_DECAY: 0.0001
ALPHA: 0.4
